# ===========================================
# Site Information Settings
# ===========================================

# æ˜¯å¦å…è®¸ç”¨æˆ·å¤åˆ¶ç½‘ç«™ä¸Šçš„å†…å®¹ï¼Œä»…ä»…æ˜¯å›å­åå®š
selectable: true

# æ–‡å­—æ˜¯å¦ç¼©è¿›ï¼ˆ2å­—ç¬¦ï¼‰
text_indent: true

# Dark mode
# Available values: true, false, auto
dark_mode: auto

# Round corner
# Warning: This feature is NOT fully tested on various browsers.
smooth_corner: false

# Code settings
code:
  # Force hide line numbers
  line_number: false

# Counting words
word_count:
  enable: true
  mode: all # or en_only | zh_only
  reading_time: false
  reading_speed:
    cn: 300
    en: 160

# Site creation time
since: 2018

# key: link text, value: URL link
header_menu:
  About: /about

# æ–‡ç« å³ä¾§TOCå¯¼èˆª
# å¯¹äºæ¯ç¯‡æ–‡ç« ï¼Œéƒ½å¯ä»¥ä½¿ç”¨"toc: false|true"æŒ‡å®šæ˜¯å¦æ˜¾ç¤ºtoc
# ä¸è®¾ç½®åˆ™é»˜è®¤ä¸ä¸‹é¢çš„toc.enableä¿æŒä¸€è‡´
toc:
  enable: true
  list_number: true  # æ˜¯å¦æ˜¾ç¤ºæ•°å­—æ’åº

# A sentence to show
signature: ğŸ‘¾é³ç‰‡ä¸ä¹±ç ï¼šã€Œå¤š æ™’ æœˆ äº®ã€âœ¨

comment:
  enable: false
  type: 'gitalk' # gitalk or valine
  # config for valine
  placeholder: 'Just go go.'
  app_id:
  app_key:
  # config for gitalk
  client_id:
  client_secret:
  repo:
  owner:
  admin: []

# æ˜¯å¦æ˜¾ç¤ºâ€œæ›´å¤šâ€æŒ‰é’®
excerpt_link: true

# æ˜¯å¦åŠ è½½è¾…åŠ©æ ·å¼
helpers: true

favicon: /img/favicon.ico

# æ­¤å¤„è¯·è®¾ç½®ä¸æ ¹ç›®å½•ä¸‹_config.ymlé‡Œçš„rootä¸€è‡´ï¼ˆä¸€èˆ¬åœ¨urlçš„ä¸‹ä¸€è¡Œï¼‰
root: /

# ===========================================
# Version
# ===========================================
version: v3.2.5
